import { Link } from 'react-router-dom'
import { ArrowLeft } from 'lucide-react'

const CONTACT_EMAIL = 'ty@infiniteawesomestudio.com'
const LAST_UPDATED = 'May 8, 2026'

export default function Terms() {
  return (
    <div className="min-h-screen bg-dark-base text-dark-text">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 py-16">
        <Link to="/" className="inline-flex items-center gap-2 text-sm font-body text-dark-muted hover:text-mint transition-colors mb-10">
          <ArrowLeft size={16} /> Back to BeneBots
        </Link>

        <h1 className="font-display font-bold text-3xl sm:text-4xl mb-2">Terms of Service</h1>
        <p className="text-sm font-body text-dark-muted mb-12">Last updated: {LAST_UPDATED}</p>

        <div className="space-y-10 text-sm font-body text-dark-muted leading-relaxed">
          <section>
            <h2 className="font-display font-semibold text-lg text-dark-text mb-3">Agreement</h2>
            <p>
              By accessing or using BeneBots ("the Service"), operated by Infinite Awesome Studio ("we," "us"), you agree to these Terms of Service. If you do not agree, do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="font-display font-semibold text-lg text-dark-text mb-3">What BeneBots Is</h2>
            <p>
              BeneBots provides AI-powered demo tools for employee benefits administration. The demos are for illustrative purposes and are designed to show how AI agents can assist benefits professionals.
            </p>
          </section>

          <section>
            <h2 className="font-display font-semibold text-lg text-dark-text mb-3">Not Professional Advice</h2>
            <p>
              BeneBot responses are generated by AI and are <strong className="text-dark-text">not</strong> professional benefits, legal, medical, or financial advice. Always verify AI-generated information against your plan documents and consult qualified professionals for decisions affecting employee benefits.
            </p>
          </section>

          <section>
            <h2 className="font-display font-semibold text-lg text-dark-text mb-3">Appropriate Use</h2>
            <p className="mb-3">When using BeneBots, you agree not to:</p>
            <ul className="list-disc pl-5 space-y-2">
              <li>Input real protected health information (PHI), Social Security numbers, or other sensitive personal data into demos.</li>
              <li>Use the Service for any unlawful purpose.</li>
              <li>Attempt to reverse-engineer, exploit, or interfere with the Service's operation.</li>
              <li>Misrepresent AI-generated outputs as certified professional advice.</li>
            </ul>
          </section>

          <section>
            <h2 className="font-display font-semibold text-lg text-dark-text mb-3">Intellectual Property</h2>
            <p>
              All content, design, branding, and code on this site are owned by Infinite Awesome Studio. You may not copy, reproduce, or distribute any part of the Service without written permission.
            </p>
          </section>

          <section>
            <h2 className="font-display font-semibold text-lg text-dark-text mb-3">Availability</h2>
            <p>
              We aim to keep BeneBots available but make no guarantees of uptime. We may modify, suspend, or discontinue any part of the Service at any time without notice.
            </p>
          </section>

          <section>
            <h2 className="font-display font-semibold text-lg text-dark-text mb-3">Limitation of Liability</h2>
            <p>
              To the fullest extent permitted by law, Infinite Awesome Studio shall not be liable for any indirect, incidental, or consequential damages arising from your use of the Service. The Service is provided "as is" without warranties of any kind.
            </p>
          </section>

          <section>
            <h2 className="font-display font-semibold text-lg text-dark-text mb-3">Changes to These Terms</h2>
            <p>
              We may update these terms from time to time. Continued use of the Service after changes constitutes acceptance of the revised terms.
            </p>
          </section>

          <section>
            <h2 className="font-display font-semibold text-lg text-dark-text mb-3">Contact</h2>
            <p>
              Questions about these terms? Email us at{' '}
              <a href={`mailto:${CONTACT_EMAIL}`} className="text-mint hover:underline">{CONTACT_EMAIL}</a>.
            </p>
          </section>
        </div>
      </div>
    </div>
  )
}
